on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 11
          target-folder: "${GITHUB_REF##*/}"
          project: maven
        env:
          MAVEN_OPTS: "-Dmaven.javadoc.failOnError=false"
